version: '3.8'

secrets:
  pass :
    file : ./db_pass.txt

services:
  # mysql:
  #   image: sameersbn/mysql:5.7.22-1
  #   environment:
  #     - DB_USER=redmine
  #     - DB_PASS=password
  #     - DB_NAME=redmine_production
  #   volumes:
  #     - /srv/docker/redmine/mysql:/var/lib/mysql
  
    
  redmine:
    build: ./
    image: sameersbn/redmine:5.0.4
    network_mode: bridge
    # depends_on:
    #   - mysql
    extra_hosts:
    - "host.docker.internal:host-gateway"
    
    environment:
      
      - TZ=Asia/Kolkata

      - DB_ADAPTER=mysql2
      - DB_HOST=10.0.2.15
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS_FILE=/run/secrets/pass
      - DB_NAME=redmine_production
      - DB_SSL_MODE=prefer

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=cloudadmin@shrinesoft.com
      - SMTP_PASS=King@9601
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:plain

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30
    secrets:
      - pass
    ports:
      - "10083:80"
    volumes:
      - /home/darsh/Documents/redmine:/home/redmine/data
      - /home/darsh/Documents/redmine_log:/var/log/redmine