version: '2'

services:
  # mysql:
  #   image: sameersbn/mysql:5.7.22-1
  #   environment:
  #     - DB_USER=redmine
  #     - DB_PASS=password
  #     - DB_NAME=redmine_production
  #   volumes:
  #     - /srv/docker/redmine/mysql:/var/lib/mysql
  redmine:
    extra_hosts:
    - "host.docker.internal:host-gateway"
    build: ./
    image: sameersbn/redmine:5.0.4
    # depends_on:
    #   - mysql
    environment:
      - TZ=Asia/Kolkata

      - DB_ADAPTER=mysql2
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=darsh@Savani1
      - DB_NAME=redmine_production
      - DB_SSL_MODE=prefer

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=test@gmail.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:80"
    volumes:
      - /home/darsh/Documents/redmine:/home/redmine/data
      - /home/darsh/Documents/redmine_log:/var/log/redmine
