version: '3.8'

secrets:
  pass :
    file : ./db_pass.txt
  db_user :
    file : ./db_user.txt
  db_name : 
    file : ./db_name.txt
  smtp_user :
    file : ./smtp_user.txt
  smtp_pass : 
    file : ./smtp_pass.txt 

volumes:
  redfile:
    name: ${REDMINE_FILE}
  logfile:
    name: ${REDMINE_LOG}    

services:
    
  redmine:
    build: ./
    image: sameersbn/redmine:5.0.4
    network_mode: bridge
    
    extra_hosts:
    - "host.docker.internal:host-gateway"
    
    environment:
      
      - TZ=Asia/Kolkata

      - DB_ADAPTER=mysql2
      - DB_HOST=10.0.2.15
      - DB_PORT=3306
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASS_FILE=/run/secrets/pass
      - DB_NAME_FILE=/run/secrets/db_name
      - DB_SSL_MODE=prefer

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER_FILE=/run/secrets/smtp_user
      - SMTP_PASS_FILE=/run/secrets/smtp_pass
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:plain

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30
    secrets:
      - db_user
      - pass
      - db_name
      - smtp_user
      - smtp_pass 
      
    ports:
      - "10083:80"
   
    volumes:
      - redfile:/home/redmine/data
      - logfile:/var/log/redmine
    